//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Music_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSong
    {
        public int song_id { get; set; }
        public string song_name { get; set; }
        public string song_artist { get; set; }
        public string song_category { get; set; }
        public string language { get; set; }
        public string lyrics { get; set; }
    }
}
